"""app settings knowledge_writable toggle

Revision ID: 1ef68d6f8ac7
Revises: a346dd2c2dad
Create Date: 2026-07-03 02:56:02.303613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型（AutoString 等）渲染依赖


# revision identifiers, used by Alembic.
revision: str = '1ef68d6f8ac7'
down_revision: Union[str, None] = 'a346dd2c2dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_writable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appsetting')
    # ### end Alembic commands ###
