"""MET-12 campaign pool ref link table

Revision ID: 25f37d24f036
Revises: 301fc66319a3
Create Date: 2026-07-04 00:46:08.747628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型（AutoString 等）渲染依赖


# revision identifiers, used by Alembic.
revision: str = '25f37d24f036'
down_revision: Union[str, None] = '301fc66319a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaignpoolref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('pool_topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['pool_topic_id'], ['pooltopic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaignpoolref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaignpoolref_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaignpoolref_pool_topic_id'), ['pool_topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaignpoolref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaignpoolref_pool_topic_id'))
        batch_op.drop_index(batch_op.f('ix_campaignpoolref_campaign_id'))

    op.drop_table('campaignpoolref')
    # ### end Alembic commands ###
