"""MET-16 llmsetting image text/image split columns

Revision ID: 301fc66319a3
Revises: 1ef68d6f8ac7
Create Date: 2026-07-03 05:15:37.040397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型（AutoString 等）渲染依赖


# revision identifiers, used by Alembic.
revision: str = '301fc66319a3'
down_revision: Union[str, None] = '1ef68d6f8ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default 让已有行（如 MET-13 建的单行设置）拿到默认值——
    # 否则给非空表加 NOT NULL 列会失败（Postgres 报错 / SQLite batch 填 NULL 违约）。
    with op.batch_alter_table('llmsetting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_base_url', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default='https://api.minimax.chat/v1'))
        batch_op.add_column(sa.Column('image_api_key', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('image_model', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default='image-01'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llmsetting', schema=None) as batch_op:
        batch_op.drop_column('image_model')
        batch_op.drop_column('image_api_key')
        batch_op.drop_column('image_base_url')

    # ### end Alembic commands ###
