"""MET-13 llm settings

Revision ID: a346dd2c2dad
Revises: e5bcd93b5873
Create Date: 2026-07-02 23:41:38.900362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型（AutoString 等）渲染依赖


# revision identifiers, used by Alembic.
revision: str = 'a346dd2c2dad'
down_revision: Union[str, None] = 'e5bcd93b5873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmsetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openai_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openai_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claude_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llmsetting')
    # ### end Alembic commands ###
