"""MET-12 brand doc analysis fields (tngen)

Revision ID: b100a49321c2
Revises: 25f37d24f036
Create Date: 2026-07-04 01:58:52.729718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型（AutoString 等）渲染依赖


# revision identifiers, used by Alembic.
revision: str = 'b100a49321c2'
down_revision: Union[str, None] = '25f37d24f036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default 让已有行（默认品牌 + 已有文档）拿到默认值，避免加 NOT NULL 列失败
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('style_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('analysis_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='idle'))
        batch_op.add_column(sa.Column('analysis_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.drop_column('brand_digest')

    with op.batch_alter_table('branddoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('style_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('deep_read', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branddoc', schema=None) as batch_op:
        batch_op.drop_column('deep_read')
        batch_op.drop_column('style_summary')
        batch_op.drop_column('ai_analysis')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_digest', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('analysis_error')
        batch_op.drop_column('analysis_status')
        batch_op.drop_column('style_digest')
        batch_op.drop_column('doc_digest')

    # ### end Alembic commands ###
