"""MET-12 add extracted_text to docs

Revision ID: e5bcd93b5873
Revises: eba59f412171
Create Date: 2026-07-02 23:00:41.138692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型（AutoString 等）渲染依赖


# revision identifiers, used by Alembic.
revision: str = 'e5bcd93b5873'
down_revision: Union[str, None] = 'eba59f412171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branddoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    with op.batch_alter_table('campaigndoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigndoc', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')

    with op.batch_alter_table('branddoc', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')

    # ### end Alembic commands ###
